# Generated by Django 5.1.6 on 2025-02-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='browserdetail',
            old_name='platform',
            new_name='os',
        ),
    ]
