# Generated by Django 5.1.6 on 2025-02-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_rename_platform_browserdetail_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='browserdetail',
            name='agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='browserdetail',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
